# Generated by Django 4.0.4 on 2022-06-07 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=30)),
                ('Last_Name', models.CharField(max_length=30)),
                ('Age', models.PositiveIntegerField(blank=True, null=True)),
                ('Nationality', models.CharField(max_length=30)),
                ('Freelance', models.CharField(default='Avaliable', max_length=30)),
                ('Address', models.CharField(max_length=30)),
                ('Phone', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Skype', models.EmailField(max_length=254)),
                ('Languages', models.CharField(max_length=30)),
            ],
        ),
    ]
